apiVersion: v1
kind: Template
metadata:
  name: keycoak-cluster
  annotations:
    description: "Keycloak Cluster"
    iconClass: "icon-jboss"
    tags: "keycloak"
objects:



- apiVersion: v1
  kind: ImageStream
  metadata:
    name: keycloak-cluster-base
    
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: keycloak-master-base
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: keycloak-cluster-base:latest
    resources: {}
    source:
      git:
        ref: master
        uri: https://github.com/zotovsa/keycloak-mysql.git
      contextDir: ./
      type: Git
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
